[package]
name = "romulus"
version = "0.1.0"
authors = ["eulegang<eulegang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
clap = "~2.27.0"
lazy_static = "1.3.0"
